export enum ACTIONS {
    SET_ARTICLES_ACTION = "SET_ARTICLES_ACTION",
    SET_REPORTS_ACTION = "SET_REPORTS_ACTION",
    SET_BLOGS_ACTION = "SET_BLOGS_ACTION",

    SET_SELECTED_ARTICLES_ACTION = "SET_SELECTED_ARTICLES_ACTION",
    SET_SELECTED_REPORTS_ACTION = "SET_SELECTED_REPORTS_ACTION",
    SET_SELECTED_BLOGS_ACTION = "SET_SELECTED_BLOGS_ACTION",
    SET_NEWS_ERROR_ACTION = "SET_NEWS_ERROR_ACTION",

    GET_ARTICLES_ACTION = "GET_ARTICLES_ACTION",
    GET_REPORTS_ACTION = "GET_REPORTS_ACTION",
    GET_BLOGS_ACTION = "GET_BLOGS_ACTION",

    GET_SELECTED_ARTICLES_ACTION = "GET_SELECTED_ARTICLES_ACTION",
    GET_SELECTED_REPORTS_ACTION = "GET_SELECTED_REPORTS_ACTION",
    GET_SELECTED_BLOGS_ACTION = "GET_SELECTED_BLOGS_ACTION",
    GET_NEWS_ERROR_ACTION = "GET_NEWS_ERROR_ACTION",

    GET_PAGINATED_ARTICLE_ACTION = "GET_PAGINATED_ARTICLE_ACTION",
    GET_PAGINATED_BLOG_ACTION = "GET_PAGINATED_BLOG_ACTION",
    GET_PAGINATED_REPORT_ACTION = "GET_PAGINATED_REPORT_ACTION",

    SET_PAGINATION_ARTICLE_ACTION = "SET_PAGINATED_ARTICLE_ACTION",
    SET_PAGINATION_BLOG_ACTION = "SET_PAGINATION_BLOG_ACTION",
    SET_PAGINATION_REPORT_ACTION = "SET_PAGINATION_REPORT_ACTION",

    GET_SORTED_ARTICLE_ACTION = "GET_SORTED_ARTICLE_ACTION",
    GET_SORTED_BLOG_ACTION = "GET_SORTED_BLOG_ACTION",
    GET_SORTED_REPORT_ACTION = "GET_SORTED_REPORT_ACTION",


    GET_SEARCH_ARTICLE_ACTION = "GET_SEARCH_ARTICLE_ACTION",
    GET_SEARCH_BLOG_ACTION = "GET_SEARCH_BLOG_ACTION",
    GET_SEARCH_REPORT_ACTION = "GET_SEARCH_REPORT_ACTION",

}